### PR TITLE
chore: add extension method over ControllerBase

### PR DESCRIPTION
**Pull request by shahabganji**
An extension method added for ControllerBase which takes a Result<T>
and converts that to ActionResult<T>.

@ardalis , I am afraid we cannot use `ActionFilter` since the `Result` property in the context of all filters is of type `IActionResult` so we are losing the `T` type. If you found any other solutions except the extension method over controller I will be more than happy to hear about that too. 

I was also thinking about inheritance over conversion, but in that case, the library won't be general as it requires to reference some asp.net core libs. and it won't have access to the `ModelState` of the controller too.

### CODE REVIEW

**Comment by shahabganji** [comment]
@ardalis, I've made some changes not the best solution but it works with a filter. I am still thinking for a better solution, however, I think this handles the situation

**Comment by shahabganji** [comment]
@ardalis , I think now it is what you are looking for

**Comment by ardalis** [comment]
Thanks! I think the only thing missing is in the "Ok" case it should return the Value not the Result<T> with the Ok.

**Comment by ardalis** [comment]
I think I got it.

**Comment by shahabganji** [comment]
Great, I would like to know the solution

**Pull request merged**
