### PR TITLE
Change ValidationErrors to Dictionary<string, string[]>

### PR DESCRIPTION
**Pull request by pauldbentley**
Hi Steve,

This changes ValidationErrors to allow mutiple errors for the same key.

I wasn't sure how to update the Nuget links, so I have commented out the package references and just added in a project references.  I presume this is something you can check and change?

Thanks

Paul

### CODE REVIEW

**Comment by ardalis** [comment]
It’s a two step process. You have to update and publish the base package then update to use it in the other one and deploy it. I’ll sort that part out. Thanks!

**Comment by SimonGeering** [comment]
This is a breaking change so at a minimum should have an appropriate major version bump since there has already been getting on for 200 downloads.

**Comment by ardalis** [comment]
Good point; I'll get the versions sorted out as well (with version bumps).

**Comment by SimonGeering** [comment]
This is also something of interest in the context of what a validation result means. 
Something I have commented further on here: <https://github.com/ardalis/Result/issues/16#issuecomment-630255263>

**Comment by ardalis** [comment]
Thanks @pauldbentley - we ended up incorporating a lot of this into a couple of other recent PRs. Cheers!

**Comment by pauldbentley** [comment]
Thanks @ardalis - it's great to see this package developing.

FYI - I've been using my [own package](https://github.com/pauldbentley/results) while this one evolves, my ultimate aim is to use your package.

I've got a few differences in-case they were useful:

- I have a generic and non-generic version of `Result`, this allows for results that don't return a value.
- The result static methods all hang off `Result` which helps with [CA1000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1000?view=vs-2019).

This makes the code:

```cs
return Result<IEnumerable<WeatherForecast>>.NotFound();
```

Become:

```cs
return Result.NotFound<IEnumerable<WeatherForecast>>();
```

- I have an overload for `Error()` which takes an `object problem` I find this useful for returning a `ProblemDetails` from a WebAPI.
- I have separate concrete classes such as `OkResult`, and `ErrorResult` to help building results.

**Pull request closed without merging**
