### PR TITLE
ToActionResult Extention method on Result<T>

### PR DESCRIPTION
**Pull request by JelmarVA**
An extention method added as mentioned in issue #59

### CODE REVIEW

**Review by ardalis — CHANGES_REQUESTED** [review]
Thanks! Can you change `Extention` to `Extension` throughout please?

**Comment by ardalis** [comment]
@TopSwagCode have a look since you were involved in this as well?

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Ok one more time - can you check and see why the build is failing with this?

```
Error: /home/runner/work/Result/Result/src/Ardalis.Result.AspNetCore/ResultExtensions.cs(76,39): error CS0111: Type 'ResultExtensions' already defines a member called 'ToActionResult' with the same parameter types [/home/runner/work/Result/Result/src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj]
  Ardalis.Result.UnitTests -> /home/runner/work/Result/Result/tests/Ardalis.Result.UnitTests/bin/Release/net5.0/Ardalis.Result.UnitTests.dll
  Successfully created package '/home/runner/work/Result/Result/src/Ardalis.Result.FluentValidation/bin/Release/Ardalis.Result.FluentValidation.3.0.2.nupkg'.
  Ardalis.Result.Sample.Core -> /home/runner/work/Result/Result/sample/Ardalis.Result.Sample.Core/bin/Release/netstandard2.0/Ardalis.Result.Sample.Core.dll
  Ardalis.Result.Sample.UnitTests -> /home/runner/work/Result/Result/sample/Ardalis.Result.Sample.UnitTests/bin/Release/net5.0/Ardalis.Result.Sample.UnitTests.dll

Build FAILED.

Error: /home/runner/work/Result/Result/src/Ardalis.Result.AspNetCore/ResultExtensions.cs(76,39): error CS0111: Type 'ResultExtensions' already defines a member called 'ToActionResult' with the same parameter types [/home/runner/work/Result/Result/src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by JelmarVA** [comment]
The same functionality was implemented in #66.

I'll close this Pull Request.

**Pull request closed without merging**
