### PR TITLE
Add Unauthorized status

### PR DESCRIPTION
**Pull request by alexjusti**
I added an unauthorized status for an app that I'm developing.  It could be useful in differentiating from authentication and authorization issues

### CODE REVIEW

**Review by ardalis — APPROVED** [review]
Can you also update the filter so it supports both 403 and 401 as appropriate?

**Comment by alexjusti** [comment]
I implemented them both.

**Review by ardalis — APPROVED** [review]
Thanks!

**Comment by ardalis** [comment]
Hmm, build keeps failing. Can you make sure existing tests pass and perhaps add some new tests for this and commit them to this PR?

**Comment by ardalis** [comment]
Never mind. I'll sort it out after I merge. Thanks!

**Pull request merged**
